using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Envitia.MapLink;

namespace MapLinkProApp.MapLayers
{
  /// <summary>
  /// A map layer that visualises a map generated by MapLink Studio.
  /// </summary>
  public class MapLinkMapLayer : MapLayer
  {
    private Envitia.MapLink.TSLNDataLayer DataLayer { get; set; }

    public override void ConfigureMapLayer(TSLN2DDrawingSurface surface, bool visible, double depth)
    {
      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyVisible, visible ? 1 : 0);
      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyDetect, visible ? 1 : 0);

      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyTransparency, IsFoundationLayer ? 255: Opacity);

      if (DataLayer != null)
      {
        DataLayer.notifyChanged();
      }
    }

    public override TSLNDataLayer GetDataLayer()
    {
      if (DataLayer != null)
        return DataLayer;

      DataLayer = new Envitia.MapLink.TSLNMapDataLayer();
      if (!DataLayer.loadData(DataLocation))
      {
        DataLayer = null;
      }

      return DataLayer;
    }    
  }
}
