using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using Envitia.MapLink;
using Envitia.MapLink.Terrain;

namespace MapLinkProApp.MapLayers
{
  /// <summary>
  /// A map layer that visualises a map generated by MapLink Studio.
  /// </summary>
  public class MapLinkMapLayer : MapLayer
  {
    private Envitia.MapLink.TSLNDataLayer DataLayer { get; set; }
    private Envitia.MapLink.Terrain.TSLNTerrainDatabase TerrainDatabase { get; set; }

    public override void ConfigureMapLayer(TSLN2DDrawingSurface surface, bool visible, double depth)
    {
      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyVisible, visible ? 1 : 0);
      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyDetect, visible ? 1 : 0);

      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyTransparency, IsFoundationLayer ? 255: Opacity);

      if (DataLayer != null)
      {
        DataLayer.notifyChanged();
      }
    }

    public override TSLNDataLayer GetDataLayer()
    {
      if (DataLayer != null)
        return DataLayer;

      string errors = "";

      DataLayer = new Envitia.MapLink.TSLNMapDataLayer();
      if (!DataLayer.loadData(DataLocation))
      {
        DataLayer = null;
        string error = TSLNErrorStack.errorString("\nErrors:\n");
        errors += "Failed to load data: " + Property + error + "\n";
      }

      if (errors.Length > 0)
      {
        System.Windows.MessageBox.Show(errors);
      }

      return DataLayer;
    }

    public override TSLNTerrainDatabase GetTerrainDatabase()
    {
      if (TerrainDatabase != null)
        return TerrainDatabase;

      TerrainDatabase = new Envitia.MapLink.Terrain.TSLNTerrainDatabase();
      if (TerrainDatabase.open(TerrainLocation) != Envitia.MapLink.Terrain.TSLNTerrainReturn.TSLNTerrain_OK)
      {
        TerrainDatabase = null;
      }

      return TerrainDatabase;
    }
  }
}
